# Generated by Django 5.2.5 on 2025-09-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211130_0929'),
        ('recipes', '0003_alter_recipe_slug'),
    ]

    operations = [
    ]
